apiVersion: v1
kind: ConfigMap
metadata:
  name: fwd-rqsyslog
data:
  rqsyslog.conf: |
    input {
      tcp {
        port => 1470
        tags => ["syslog"]
      }
    }

    filter {
      if "syslog" in [tags] {
        uuid {
          target    => "@uuid"
          overwrite => true
        }
        mutate {
          add_field => { "fwdserver" => "${HOSTNAME:unknown.local}" }
        }
        if "76.74.255.146" in [message] {
          throttle {
            before_count => 500
            after_count => 1000
            period => 600
            key => "76.74.255.146"
            add_tag => "throttled"
          }
          if "throttled" in [tags] {
            drop { }
          }
        }
        # Drop unwanted logs
        if ",ping," in [message] {
          drop { }
        } else if "last message repeated" in [message] {
            drop { }
        }
      }
    }

    output {
      if "syslog" in [tags] {
        rabbitmq {
          exchange => "logstash-rqsyslog"
          exchange_type => "direct"
          key => "rqsyslog-key"
          host => "rabbitmq-logging"
          durable => true
          persistent => true
          user => "logstashfakeuser"
          password => "somefakepass"
        }
      }
    }

